Exit in failure when no .snap produced.
This will impact all new PR rebased on this master commit.
Fixes #8.

diff --git a/ci-run b/ci-run
--- a/ci-run
+++ b/ci-run
@@ -9,13 +9,17 @@ if [ "$current_branch" != "master" ]; then
 fi
 
 root_dir=`pwd`
+return_code=0
 for dir in $projects_to_test; do
     echo "Testing $dir"
     cd ${root_dir}/$dir
     docker run -v $(pwd):/snapcraft -t sergiusens/snapcraft sh -c "cd /snapcraft && snapcraft"
     ls *.snap
     if [ $? -ne 0 ]; then
-        echo "No .snap file built"
+        echo "FAILURE: No .snap file built"
+        return_code=1
     fi
     echo "###############################################################################"
 done
+
+exit $return_code
